pre-training:
  - experiment: 1
    learning_rate: 2e-5
    batch_size: 8
    epochs: 5
    mplm: "mdeberta-v3-base"
    threshold: 0.5
    
  - experiment: 2
    learning_rate: 2e-5
    batch_size: 8
    epochs: 5
    mplm: "mdeberta-v3-base"
    threshold: 0.7